### ISSUE TITLE
Example bug?

### ISSUE THREAD

**Issue by matkuki** [ijneb/nim-algebra#1]
Hi,

This example from the Readme.md doesn't work:
```nim
import algebra
echo evaluate(expr"a/ln(b)", {"a": 5.5, "b": 2.2})
```
but this does:
```nim
import algebra
import tables
echo evaluate(expr"a/ln(b)", {"a": 5.5, "b": 2.2}.toTable())
```

Is this a bug?

**Comment by ijneb** [comment]
What version of Nim are you using? I can't recreate this error.

There is a template that should take care of .toTable() at compilation-time: https://github.com/ijneb/nim-algebra/blob/master/algebra.nim#L148.

**Comment by matkuki** [comment]
```
Nim Compiler Version 0.19.9 [Windows: amd64]
Compiled at 2019-05-14
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 651ae68567a71085bf4c0fc58fba18d5acbbe693
active boot switches: -d:release
```

**Comment by ijneb** [comment]
Fixed the issue, thanks for alerting me :)

**Comment by matkuki** [comment]
Confirming that it works, thanks.
